# Runs all tests on master everyday at 10 am (UTC time)
name: Cron Testing

defaults:
  run:
    shell: bash

on:  # Runs on master branch on Saturdays at 12am UTC time
  schedule:
    - cron:  '* 12 * * Sat'

jobs:
  tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04, macos-latest, windows-latest]
        python-version: ["3.10", 3.11, 3.12, 3.x]  # crons should always run latest python hence 3.x
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'

      - name: Upgrade pip
        run: poetry run python -m pip install --upgrade pip

      - name: Install package with test dependencies
        run: python -m pip install ".[test]"

      - name: Run Tests
        run: python -m pytest
